### ISSUE TITLE
How to use yolov5x-seg.onnx?

### ISSUE THREAD

**Issue by winktool** [Hyuto/yolov5-onnxruntime-web#3]

**Comment by winktool** [comment]
The model link is : https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5x-seg.pt

**Comment by winktool** [comment]
How to change these codes?
```
  const dims = [1, 3, height, width];
  const imageTensor = await imageDataToTensor(image, dims);
  const feeds = {};
  feeds[session.inputNames[0]] = imageTensor;
  const results = await session.run(feeds);
  const output0 = results[session.outputNames[0]];
  const boxes = [];
  for (let r = 0; r < output0.data.length; r += output0.dims[2]) {
    const data = output0.data.slice(r, r + output0.dims[2]); // get rows
    console.log("data", output0.data);
    const scores = data.slice(5); // classes probability scores
    const confidence = data[4]; // detection confidence
    const classId = scores.indexOf(Math.max(...scores)); // class id of maximum probability scores
    const maxClassProb = scores[classId]; // maximum probability scores
    if (confidence >= confidenceThreshold && maxClassProb >= classThreshold) {
      const [x, y, w, h] = data.slice(0, 4);
      boxes.push({
        name: labels[classId],
        score: (maxClassProb * 100).toFixed(1),
        classId: classId,
        probability: maxClassProb,
        confidence: confidence,
        bounding: [x - 0.5 * w, y - 0.5 * h, w, h],
      });
    }
  }
  ```

**Comment by winktool** [comment]
Hey,bro,i found these,maybe can help us.
https://github.com/ultralytics/yolov5/issues/9746

**Comment by winktool** [comment]
Yes, I'm looking forward to your new progress.

**Comment by winktool** [comment]
Maybe this page can help us:
https://blog.csdn.net/qq_41043389/article/details/127754384

**Comment by Hyuto** [comment]
I've create new repo on deploy YOLOv5-seg on onnxruntime but in python. You can take a look here https://github.com/Hyuto/yolov5-seg-onnxruntime

**Comment by winktool** [comment]
You're a really good guy!

**Comment by winktool** [comment]
but do you know how to use them with nodejs.
python version link:https://github.com/ultralytics/yolov5/blob/master/segment/predict.py

**Comment by Hyuto** [comment]
Hello just a little bit update here, I've implemented it using onnxruntime-web although the performance is bad and can't do live detection (video), but hey IT WORKS 😁

https://github.com/Hyuto/yolov5-seg-onnxruntime-web

If any issue on yolov5-seg you can put it there. I'm closing this issue
